"""Initial migration.

Revision ID: 080a6b05055b
Revises: 64d9f7fb1e84
Create Date: 2023-09-29 10:52:15.938400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080a6b05055b'
down_revision = '64d9f7fb1e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('service', sa.Boolean(), nullable=False),
    sa.Column('item_description', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['unit'], ['unit.unit_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
