"""WarehouseOrderRow.

Revision ID: 0f7484d7afec
Revises: ed7657c6d2ee
Create Date: 2023-12-06 11:50:42.116221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7484d7afec'
down_revision = 'ed7657c6d2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_order_row',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_einvoice_row_order', sa.Integer(), nullable=False),
    sa.Column('fk_balance_order_row', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fk_balance_order_row'], ['balance_item.party_id'], ),
    sa.ForeignKeyConstraint(['fk_einvoice_row_order'], ['einvoice_row.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse_order_row')
    # ### end Alembic commands ###
