"""WarehouseOrderRow 2.

Revision ID: 1b6bab5eeb7e
Revises: 0f7484d7afec
Create Date: 2023-12-12 11:28:58.086374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6bab5eeb7e'
down_revision = '0f7484d7afec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_order_row', schema=None) as batch_op:
        batch_op.add_column(sa.Column('einvoice_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_wh_einvoice_num_doc', 'einvoice', ['einvoice_id'], ['num_doc'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_order_row', schema=None) as batch_op:
        batch_op.drop_constraint('fk_wh_einvoice_num_doc', type_='foreignkey')
        batch_op.drop_column('einvoice_id')

    # ### end Alembic commands ###
