"""Initial migration.

Revision ID: 2f7db8077a96
Revises: 080a6b05055b
Create Date: 2023-09-29 11:06:33.462253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7db8077a96'
down_revision = '080a6b05055b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('item_description',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('item_description',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
