"""GroupItem - Item.

Revision ID: 441c3bdfe198
Revises: c751abe939b0
Create Date: 2023-12-22 12:22:16.106910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441c3bdfe198'
down_revision = 'c751abe939b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False, default=1))
        batch_op.create_foreign_key('fk_item_group', 'group_item', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_group', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
