"""Pinvoce update2.

Revision ID: 61f113d8c758
Revises: f4b6041fa36b
Create Date: 2023-11-29 15:45:18.396101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f113d8c758'
down_revision = 'f4b6041fa36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinvoice_row', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinvoice_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_pinvoice_num_doc', 'pinvoice', ['pinvoice_id'], ['num_doc'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinvoice_row', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pinvoice_num_doc', type_='foreignkey')
        batch_op.drop_column('pinvoice_id')

    # ### end Alembic commands ###
