"""Initial migration.

Revision ID: 72d5ce66cb3b
Revises: 2f7db8077a96
Create Date: 2023-09-29 11:16:45.381538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d5ce66cb3b'
down_revision = '2f7db8077a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinvoice',
    sa.Column('num_doc', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer', sa.Integer(), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('doc_status', sa.Integer(), nullable=False),
    sa.Column('doc_date_approve', sa.Date(), nullable=True),
    sa.Column('custom_numdoc', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('num_doc')
    )
    op.create_table('pinvoice_row',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pinvoice', sa.Integer(), nullable=False),
    sa.Column('npp', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item'], ['item.id'], ),
    sa.ForeignKeyConstraint(['pinvoice'], ['pinvoice.num_doc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pinvoice_row')
    op.drop_table('pinvoice')
    # ### end Alembic commands ###
