"""Initial migration.

Revision ID: 76eb2fa1d351
Revises: b2f87debcbde
Create Date: 2023-09-29 11:18:30.822134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76eb2fa1d351'
down_revision = 'b2f87debcbde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_item',
    sa.Column('party_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item', sa.Integer(), nullable=False),
    sa.Column('date_receipt', sa.Date(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item'], ['item.id'], ),
    sa.PrimaryKeyConstraint('party_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance_item')
    # ### end Alembic commands ###
