"""Initial migration.

Revision ID: 848270fe3971
Revises: 72d5ce66cb3b
Create Date: 2023-09-29 11:17:32.992885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848270fe3971'
down_revision = '72d5ce66cb3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('einvoice',
    sa.Column('num_doc', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer', sa.Integer(), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('doc_status', sa.Integer(), nullable=False),
    sa.Column('doc_date_approve', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('num_doc')
    )
    op.create_table('einvoice_row',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('einvoice', sa.Integer(), nullable=False),
    sa.Column('npp', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['einvoice'], ['einvoice.num_doc'], ),
    sa.ForeignKeyConstraint(['item'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('einvoice_row')
    op.drop_table('einvoice')
    # ### end Alembic commands ###
