"""Correct BalanceItem

Revision ID: 8486ee6957bc
Revises: 0d2d160fd57d
Create Date: 2023-11-20 11:24:06.397217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8486ee6957bc'
down_revision = '0d2d160fd57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_item',
    sa.Column('party_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('date_receipt', sa.Date(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='fk_balance_item'),
    sa.PrimaryKeyConstraint('party_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance_item')
    # ### end Alembic commands ###
