"""Initial migration.

Revision ID: b2f87debcbde
Revises: 848270fe3971
Create Date: 2023-09-29 11:18:03.949491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f87debcbde'
down_revision = '848270fe3971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_order_row',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('einvoice_row', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['einvoice_row'], ['einvoice_row.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse_order_row')
    # ### end Alembic commands ###
