"""Einvoce update1.

Revision ID: dbed9a983dbb
Revises: 61f113d8c758
Create Date: 2023-12-05 12:07:58.911599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbed9a983dbb'
down_revision = '61f113d8c758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('einvoice',
    sa.Column('num_doc', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('doc_status', sa.Integer(), nullable=False),
    sa.Column('doc_date_approve', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='fk_einvoice_customer'),
    sa.PrimaryKeyConstraint('num_doc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('einvoice')
    # ### end Alembic commands ###
