"""Correct Pinvoce

Revision ID: f2d9e2b7e19a
Revises: 8486ee6957bc
Create Date: 2023-11-20 11:43:54.435883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d9e2b7e19a'
down_revision = '8486ee6957bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinvoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_pinvoice_customer', 'customer', ['customer_id'], ['id'])
        batch_op.drop_column('customer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinvoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_pinvoice_customer', type_='foreignkey')
        batch_op.create_foreign_key('fk_pi_customer', 'customer', ['customer'], ['id'])
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
