"""Pinvoce update.

Revision ID: f4b6041fa36b
Revises: 
Create Date: 2023-11-29 15:40:30.785364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b6041fa36b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinvoice_row', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_pinvoice_row_item', 'item', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinvoice_row', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pinvoice_row_item', type_='foreignkey')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
